import type { ComponentType } from "react";

export type CalcTab = "mortgage" | "affordability" | "closing" | "investment";
export type CalcRole = "buyer" | "seller" | "both";

export interface CalcEntry {
  id: string;
  name: string;
  description: string;
  icon: string; // lucide icon name — rendered in hub
  tab: CalcTab;
  role: CalcRole;
  /** Lazy-loaded component */
  load: () => Promise<{ default?: ComponentType; [key: string]: unknown }>;
  /** Named export key inside the module (defaults to component name) */
  exportName: string;
}

export const TAB_META: Record<CalcTab, { label: string; roles: CalcRole[] }> = {
  mortgage: { label: "Mortgage & Loans", roles: ["buyer"] },
  affordability: { label: "Affordability", roles: ["buyer"] },
  closing: { label: "Closing Costs", roles: ["both"] },
  investment: { label: "Investment", roles: ["both"] },
};

export const calculators: CalcEntry[] = [
  // ── Mortgage & Loans ────────────────────────────────────────
  {
    id: "mortgage",
    name: "Mortgage Calculator",
    description: "Estimate your monthly mortgage payment",
    icon: "Home",
    tab: "mortgage",
    role: "buyer",
    load: () => import("./mortgage/MortgageCalculator"),
    exportName: "MortgageCalculator",
  },
  {
    id: "amortization",
    name: "Amortization Schedule",
    description: "See how your loan balance decreases over time",
    icon: "TableProperties",
    tab: "mortgage",
    role: "buyer",
    load: () => import("./mortgage/AmortizationCalculator"),
    exportName: "AmortizationCalculator",
  },
  {
    id: "loan-comparison",
    name: "Loan Comparison",
    description: "Compare two loan scenarios side by side",
    icon: "ArrowLeftRight",
    tab: "mortgage",
    role: "buyer",
    load: () => import("./mortgage/LoanComparisonTool"),
    exportName: "LoanComparisonTool",
  },
  {
    id: "interest-rate-impact",
    name: "Interest Rate Impact",
    description: "See how rate changes affect your payment",
    icon: "TrendingUp",
    tab: "mortgage",
    role: "buyer",
    load: () => import("./mortgage/InterestRateImpact"),
    exportName: "InterestRateImpact",
  },
  {
    id: "down-payment",
    name: "Down Payment Calculator",
    description: "Plan your down payment savings goal",
    icon: "PiggyBank",
    tab: "mortgage",
    role: "buyer",
    load: () => import("./mortgage/DownPaymentCalculator"),
    exportName: "DownPaymentCalculator",
  },
  {
    id: "pmi",
    name: "PMI Calculator",
    description: "Estimate private mortgage insurance costs",
    icon: "ShieldCheck",
    tab: "mortgage",
    role: "buyer",
    load: () => import("./mortgage/PMICalculator"),
    exportName: "PMICalculator",
  },
  {
    id: "refinance",
    name: "Refinance Calculator",
    description: "See if refinancing makes financial sense",
    icon: "RefreshCw",
    tab: "mortgage",
    role: "buyer",
    load: () => import("./mortgage/RefinanceCalculator"),
    exportName: "RefinanceCalculator",
  },
  {
    id: "arm",
    name: "ARM Calculator",
    description: "Compare adjustable vs fixed rate mortgages",
    icon: "GitBranch",
    tab: "mortgage",
    role: "buyer",
    load: () => import("./mortgage/ARMCalculator"),
    exportName: "ARMCalculator",
  },

  // ── Affordability ───────────────────────────────────────────
  {
    id: "affordability",
    name: "Affordability Calculator",
    description: "Find out how much home you can afford",
    icon: "DollarSign",
    tab: "affordability",
    role: "buyer",
    load: () => import("./affordability/AffordabilityCalculator"),
    exportName: "AffordabilityCalculator",
  },
  {
    id: "dti",
    name: "Debt-to-Income Ratio",
    description: "Calculate your front-end and back-end DTI",
    icon: "Scale",
    tab: "affordability",
    role: "buyer",
    load: () => import("./affordability/DTICalculator"),
    exportName: "DTICalculator",
  },
  {
    id: "income-qualifier",
    name: "Income Qualifier",
    description: "Find the minimum income needed for a home",
    icon: "BadgeDollarSign",
    tab: "affordability",
    role: "buyer",
    load: () => import("./affordability/IncomeQualifier"),
    exportName: "IncomeQualifier",
  },
  {
    id: "expense-estimator",
    name: "Expense Estimator",
    description: "Estimate total monthly homeownership costs",
    icon: "Receipt",
    tab: "affordability",
    role: "buyer",
    load: () => import("./affordability/ExpenseEstimator"),
    exportName: "ExpenseEstimator",
  },
  {
    id: "budget-planner",
    name: "Budget Planner",
    description: "Plan your monthly budget around housing",
    icon: "Wallet",
    tab: "affordability",
    role: "buyer",
    load: () => import("./affordability/BudgetPlanner"),
    exportName: "BudgetPlanner",
  },

  // ── Closing Costs ──────────────────────────────────────────
  {
    id: "closing-cost",
    name: "Closing Cost Calculator",
    description: "Estimate your closing costs as a buyer",
    icon: "FileText",
    tab: "closing",
    role: "buyer",
    load: () => import("./closing/ClosingCostCalculator"),
    exportName: "ClosingCostCalculator",
  },
  {
    id: "closing-breakdown",
    name: "Closing Cost Breakdown",
    description: "Customize each closing cost line item",
    icon: "ClipboardList",
    tab: "closing",
    role: "buyer",
    load: () => import("./closing/ClosingCostBreakdown"),
    exportName: "ClosingCostBreakdown",
  },
  {
    id: "title-insurance",
    name: "Title Insurance",
    description: "Estimate lender and owner title insurance",
    icon: "Shield",
    tab: "closing",
    role: "buyer",
    load: () => import("./closing/TitleInsuranceCalculator"),
    exportName: "TitleInsuranceCalculator",
  },
  {
    id: "property-tax",
    name: "Property Tax Estimator",
    description: "Estimate annual and monthly property taxes",
    icon: "Landmark",
    tab: "closing",
    role: "buyer",
    load: () => import("./closing/PropertyTaxEstimator"),
    exportName: "PropertyTaxEstimator",
  },
  {
    id: "seller-net",
    name: "Seller Net Proceeds",
    description: "Calculate your net proceeds from a sale",
    icon: "Banknote",
    tab: "closing",
    role: "seller",
    load: () => import("./closing/SellerNetProceeds"),
    exportName: "SellerNetProceeds",
  },
  {
    id: "loan-estimate-compare",
    name: "Loan Estimate Comparison",
    description: "Compare loan estimates from different lenders",
    icon: "FileStack",
    tab: "closing",
    role: "both",
    load: () => import("./closing/LoanEstimateComparison"),
    exportName: "LoanEstimateComparison",
  },

  // ── Investment ─────────────────────────────────────────────
  {
    id: "cap-rate",
    name: "Cap Rate Calculator",
    description: "Calculate capitalization rate for a property",
    icon: "Percent",
    tab: "investment",
    role: "both",
    load: () => import("./investment/CapRateCalculator"),
    exportName: "CapRateCalculator",
  },
  {
    id: "cash-flow",
    name: "Cash Flow Analyzer",
    description: "Analyze monthly rental cash flow",
    icon: "ArrowDownUp",
    tab: "investment",
    role: "both",
    load: () => import("./investment/CashFlowAnalyzer"),
    exportName: "CashFlowAnalyzer",
  },
  {
    id: "cash-on-cash",
    name: "Cash-on-Cash Return",
    description: "Measure return on your invested cash",
    icon: "Coins",
    tab: "investment",
    role: "both",
    load: () => import("./investment/CashOnCashReturn"),
    exportName: "CashOnCashReturn",
  },
  {
    id: "rental-income",
    name: "Rental Income Projector",
    description: "Project rental income growth over time",
    icon: "TrendingUp",
    tab: "investment",
    role: "both",
    load: () => import("./investment/RentalIncomeProjector"),
    exportName: "RentalIncomeProjector",
  },
  {
    id: "operating-expense",
    name: "Operating Expenses",
    description: "Estimate rental property operating costs",
    icon: "Settings",
    tab: "investment",
    role: "both",
    load: () => import("./investment/OperatingExpenseEstimator"),
    exportName: "OperatingExpenseEstimator",
  },
  {
    id: "roi",
    name: "ROI Calculator",
    description: "Calculate total return on investment",
    icon: "Target",
    tab: "investment",
    role: "both",
    load: () => import("./investment/ROICalculator"),
    exportName: "ROICalculator",
  },
  {
    id: "fix-and-flip",
    name: "Fix & Flip Analysis",
    description: "Analyze potential profit from a flip",
    icon: "Hammer",
    tab: "investment",
    role: "both",
    load: () => import("./investment/FixAndFlipAnalysis"),
    exportName: "FixAndFlipAnalysis",
  },
  {
    id: "depreciation",
    name: "Depreciation Calculator",
    description: "Calculate tax depreciation benefits",
    icon: "Building",
    tab: "investment",
    role: "both",
    load: () => import("./investment/DepreciationCalculator"),
    exportName: "DepreciationCalculator",
  },
  {
    id: "1031-exchange",
    name: "1031 Exchange Qualifier",
    description: "Check 1031 exchange requirements and gains",
    icon: "ArrowRightLeft",
    tab: "investment",
    role: "both",
    load: () => import("./investment/ExchangeQualifier1031"),
    exportName: "ExchangeQualifier1031",
  },
];
